package constant

type AdminModule int

const (
	ADMINMODULE_CMS AdminModule = iota
	ADMINMODULE_COMMON
	ADMINMODULE_EXCHANGE
	ADMINMODULE_FINANCE
	ADMINMODULE_MEMBER
	ADMINMODULE_OTC
	ADMINMODULE_SYSTEM
	ADMINMODULE_PROMOTION
	ADMINMODULE_INDEX
	ADMINMODULE_IEO
	ADMINMODULE_GIFT
	ADMINMODULE_MARGIN
)

func (this AdminModule) String() string {
	switch this {
	case ADMINMODULE_CMS:
		return "CMS"
	case ADMINMODULE_COMMON:
		return "COMMON"
	case ADMINMODULE_EXCHANGE:
		return "EXCHANGE"
	case ADMINMODULE_FINANCE:
		return "FINANCE"
	case ADMINMODULE_MEMBER:
		return "MEMBER"
	case ADMINMODULE_OTC:
		return "OTC"
	case ADMINMODULE_SYSTEM:
		return "SYSTEM"
	case ADMINMODULE_PROMOTION:
		return "PROMOTION"
	case ADMINMODULE_INDEX:
		return "INDEX"
	case ADMINMODULE_IEO:
		return "IEO"
	case ADMINMODULE_GIFT:
		return "GIFT"
	case ADMINMODULE_MARGIN:
		return "MARGIN"
	}
	return ""
}
