package constant

type CertifiedBusinessStatus int

const (
	CERTIFIEDBUSINESSSTATUS_NOT_CERTIFIED CertifiedBusinessStatus = iota
	CERTIFIEDBUSINESSSTATUS_AUDITING
	CERTIFIEDBUSINESSSTATUS_VERIFIED
	CERTIFIEDBUSINESSSTATUS_FAILED
	CERTIFIEDBUSINESSSTATUS_DEPOSIT_LESS
	CERTIFIEDBUSINESSSTATUS_CANCEL_AUTH
	CERTIFIEDBUSINESSSTATUS_RETURN_FAILED
	CERTIFIEDBUSINESSSTATUS_RETURN_SUCCESS
)

func (this CertifiedBusinessStatus) String() string {
	switch this {
	case CERTIFIEDBUSINESSSTATUS_NOT_CERTIFIED:
		return "未认证"
	case CERTIFIEDBUSINESSSTATUS_AUDITING:
		return "认证-待审核"
	case CERTIFIEDBUSINESSSTATUS_VERIFIED:
		return "认证-审核成功"
	case CERTIFIEDBUSINESSSTATUS_FAILED:
		return "认证-审核失败"
	case CERTIFIEDBUSINESSSTATUS_DEPOSIT_LESS:
		return "保证金不足"
	case CERTIFIEDBUSINESSSTATUS_CANCEL_AUTH:
		return "退保-待审核"
	case CERTIFIEDBUSINESSSTATUS_RETURN_FAILED:
		return "退保-审核失败"
	case CERTIFIEDBUSINESSSTATUS_RETURN_SUCCESS:
		return "退保-审核成功"
	}
	return ""
}
