package constant

type TransactionType int

const (
	TRANSACTIONTYPE_RECHARGE TransactionType = iota
	TRANSACTIONTYPE_WITHDRAW
	TRANSACTIONTYPE_TRANSFER_ACCOUNTS
	TRANSACTIONTYPE_EXCHANGE
	TRANSACTIONTYPE_OTC_BUY
	TRANSACTIONTYPE_OTC_SELL
	TRANSACTIONTYPE_ACTIVITY_AWARD
	TRANSACTIONTYPE_PROMOTION_AWARD
	TRANSACTIONTYPE_DIVIDEND
	TRANSACTIONTYPE_VOTE
	TRANSACTIONTYPE_ADMIN_RECHARGE
	TRANSACTIONTYPE_MATCH
	TRANSACTIONTYPE_DEPOSIT
	TRANSACTIONTYPE_GET_BACK_DEPOSIT
	TRANSACTIONTYPE_LEGAL_RECHARGE
	TRANSACTIONTYPE_ASSET_EXCHANGE
	TRANSACTIONTYPE_CHANNEL_AWARD
	TRANSACTIONTYPE_TRANSFER_INTO_LEVER
	TRANSACTIONTYPE_TRANSFER_OUT_LEVER
	TRANSACTIONTYPE_MANUAL_AIRDROP
	TRANSACTIONTYPE_LOCK_POSITION
	TRANSACTIONTYPE_UNLOCK_POSITION
	TRANSACTIONTYPE_THIRD_PARTY_TRANSFER
	TRANSACTIONTYPE_THIRD_PARTY_TURN_OUT
	TRANSACTIONTYPE_COIN_TWO_OTC
	TRANSACTIONTYPE_OTC_TWO_COIN
	TRANSACTIONTYPE_LOAN_RECORD
	TRANSACTIONTYPE_REPAYMENT_LOAN
)

func (this TransactionType) String() string {
	switch this {
	case TRANSACTIONTYPE_RECHARGE:
		return "充值"
	case TRANSACTIONTYPE_WITHDRAW:
		return "提现"
	case TRANSACTIONTYPE_TRANSFER_ACCOUNTS:
		return "转账"
	case TRANSACTIONTYPE_EXCHANGE:
		return "币币交易"
	case TRANSACTIONTYPE_OTC_BUY:
		return "法币买入"
	case TRANSACTIONTYPE_OTC_SELL:
		return "法币卖出"
	case TRANSACTIONTYPE_ACTIVITY_AWARD:
		return "活动奖励"
	case TRANSACTIONTYPE_PROMOTION_AWARD:
		return "推广奖励"
	case TRANSACTIONTYPE_DIVIDEND:
		return "分红"
	case TRANSACTIONTYPE_VOTE:
		return "投票"
	case TRANSACTIONTYPE_ADMIN_RECHARGE:
		return "人工充值"
	case TRANSACTIONTYPE_MATCH:
		return "配对"
	case TRANSACTIONTYPE_DEPOSIT:
		return "缴纳商家认证保证金"
	case TRANSACTIONTYPE_GET_BACK_DEPOSIT:
		return "退回商家认证保证金"
	case TRANSACTIONTYPE_LEGAL_RECHARGE:
		return "法币充值"
	case TRANSACTIONTYPE_ASSET_EXCHANGE:
		return "币币兑换"
	case TRANSACTIONTYPE_CHANNEL_AWARD:
		return "渠道推广"
	case TRANSACTIONTYPE_TRANSFER_INTO_LEVER:
		return "划转入杠杆钱包"
	case TRANSACTIONTYPE_TRANSFER_OUT_LEVER:
		return "从杠杆钱包划转出"
	case TRANSACTIONTYPE_MANUAL_AIRDROP:
		return "钱包空投"
	case TRANSACTIONTYPE_LOCK_POSITION:
		return "锁仓"
	case TRANSACTIONTYPE_UNLOCK_POSITION:
		return "解锁"
	case TRANSACTIONTYPE_THIRD_PARTY_TRANSFER:
		return "第三方转入"
	case TRANSACTIONTYPE_THIRD_PARTY_TURN_OUT:
		return "第三方转出"
	case TRANSACTIONTYPE_COIN_TWO_OTC:
		return "币币转入法币"
	case TRANSACTIONTYPE_OTC_TWO_COIN:
		return "法币转入币币"
	case TRANSACTIONTYPE_LOAN_RECORD:
		return "借贷流水"
	case TRANSACTIONTYPE_REPAYMENT_LOAN:
		return "还款流水"
	}
	return ""
}
